services:

  docling:
    # image: quay.io/docling-project/docling-serve:v1.17.0
    # image: ghcr.io/k5-mot/docling-serve-jp:v1.17.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_TAG: v1.17.0
    container_name: docling-jp
    restart: unless-stopped
    environment:
      DOCLING_SERVE_HOST: 0.0.0.0
      DOCLING_SERVE_PORT: 5001
      DOCLING_SERVE_ENABLE_UI: "true"
      DOCLING_SERVE_API_KEY: "sk-docling-serve-api-key"
      DOCLING_SERVE_ARTIFACTS_PATH: /opt/app-root/src/.cache/docling/models
      DOCLING_SERVE_LOAD_MODELS_AT_BOOT: "false"
      DOCLING_SERVE_MAX_SYNC_WAIT: 36000
    ports:
      - 50001:5001
    volumes:
      - docling-data:/data
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  docling-data:
